<?xml version="1.0" encoding="utf-8"?><Database Name="Assignment_WebService" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-L2AT6ON;Initial Catalog=Assignment_WebService;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Assignment_WebServiceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Address" Member="Address">
    <Type Name="Address">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProvindsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WardsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Wards_Address" Member="Wards" ThisKey="WardsId" OtherKey="Id" Type="Wards" IsForeignKey="true" />
      <Association Name="Districts_Address" Member="Districts" ThisKey="DistrictsId" OtherKey="Id" Type="Districts" IsForeignKey="true" />
      <Association Name="Provinds_Address" Member="Provinds" ThisKey="ProvindsId" OtherKey="Id" Type="Provinds" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Wards" Member="Wards">
    <Type Name="Wards">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DistrictsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Wards_Address" Member="Address" ThisKey="Id" OtherKey="WardsId" Type="Address" />
      <Association Name="Districts_Wards" Member="Districts" ThisKey="DistrictsId" OtherKey="Id" Type="Districts" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admin">
    <Type Name="Admin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryPlace" Member="CategoryPlace">
    <Type Name="CategoryPlace">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comment">
    <Type Name="Comment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Comment" Member="Comment1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlaceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Districts" Member="Districts">
    <Type Name="Districts">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ProvindsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Districts_Address" Member="Address" ThisKey="Id" OtherKey="DistrictsId" Type="Address" />
      <Association Name="Districts_Wards" Member="Wards" ThisKey="Id" OtherKey="DistrictsId" Type="Wards" />
      <Association Name="Provinds_Districts" Member="Provinds" ThisKey="ProvindsId" OtherKey="Id" Type="Provinds" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Image" Member="Image">
    <Type Name="Image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Image" Member="Image1" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PlaceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Place" Member="Place">
    <Type Name="Place">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Information" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryPlaceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Provinds" Member="Provinds">
    <Type Name="Provinds">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Provinds_Address" Member="Address" ThisKey="Id" OtherKey="ProvindsId" Type="Address" />
      <Association Name="Provinds_Districts" Member="Districts" ThisKey="Id" OtherKey="ProvindsId" Type="Districts" />
    </Type>
  </Table>
  <Table Name="dbo.Rating" Member="Rating">
    <Type Name="Rating">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SubComment" Member="SubComment">
    <Type Name="SubComment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>